# {{ ansible_managed }}
version: "3.8"

services:
  discordbot:
    image: "{{ discordbot_docker_image }}"
    restart: "unless-stopped"
    volumes:
      - "{{ discordbot_data_path }}:/opt/redbot/data"
    environment:
      - DEFAULT_INTENTS_PATH=/opt/redbot/data/default-intents.json
      - LOGGING_CONFIG=/opt/redbot/data/discordbot-logging.yml
    command: redbot westmarches --mentionable --token=${DISCORD_BOT_SECRET} --prefix=YVwWFZyjiFQH --owner=${DISCORD_OWNER_ID}
