# {{ ansible_managed }}
version: "3.8"

services:
  discordbot:
    image: ishtanzar/wm-discord-speaker:latest
    restart: "unless-stopped"
    volumes:
      - "{{ discordbot_data_path }}:/opt/redbot/data"
    environment:
      - "DEFAULT_INTENTS_PATH=/opt/redbot/data/default-intents.json"
    command: redbot westmarches --mentionable --token=${DISCORD_BOT_SECRET} --prefix=YVwWFZyjiFQH --owner=${DISCORD_OWNER_ID}
