apiVersion: 1

datasources:
  - name: InfluxDB-Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: {{ INFLUXDB_ADMIN_TOKEN }}
    jsonData:
      version: Flux
      organization: westmarchesdelacave
      defaultBucket: bucket0
      tlsSkipVerify: true
