all:
  vars:
    SCW_ACCESS_KEY: "{{ lookup('env', 'SCW_ACCESS_KEY') }}"
    SCW_SECRET_KEY: "{{ lookup('env', 'SCW_SECRET_KEY') }}"
    SCW_REGION: "{{ lookup('env', 'SCW_REGION') }}"
    FOUNDRY_BUCKET_ACCESS_KEY_ID: "{{ lookup('env', 'FOUNDRY_BUCKET_ACCESS_KEY_ID') }}"
    FOUNDRY_BUCKET_SECRET_ACCESS_KEY: "{{ lookup('env', 'FOUNDRY_BUCKET_SECRET_ACCESS_KEY') }}"
    SCW_VOLUME_ID: "{{ lookup('env', 'SCW_VOLUME_ID') }}"
    OAUTH_CLIENT: "{{ lookup('env', 'OAUTH_CLIENT') }}"
    OAUTH_SECRET: "{{ lookup('env', 'OAUTH_SECRET') }}"
    DISCORD_BOT_SECRET: "{{ lookup('env', 'DISCORD_BOT_SECRET') }}"
    DISCORD_OWNER_ID: "{{ lookup('env', 'DISCORD_OWNER_ID') }}"
    DISCORD_BOT_PUBLIC_KEY: "{{ lookup('env', 'DISCORD_BOT_PUBLIC_KEY') }}"
    DISCORD_AWS_ACCESS_KEY_ID: "{{ lookup('env', 'DISCORD_AWS_ACCESS_KEY_ID') }}"
    DISCORD_AWS_SECRET_KEY: "{{ lookup('env', 'DISCORD_AWS_SECRET_KEY') }}"
    DISCORD_AWS_REGION: "{{ lookup('env', 'DISCORD_AWS_REGION') }}"
    KANKA_TOKEN: "{{ lookup('env', 'KANKA_TOKEN') }}"
    KANKA_CAMPAIGN: "{{ lookup('env', 'KANKA_CAMPAIGN') }}"
    KANKA_OAUTH_CLIENT: "{{ lookup('env', 'KANKA_OAUTH_CLIENT') }}"
    KANKA_OAUTH_SECRET: "{{ lookup('env', 'KANKA_OAUTH_SECRET') }}"
    INFLUXDB_ADMIN_SECRET: "{{ lookup('env', 'INFLUXDB_ADMIN_SECRET') }}"
    INFLUXDB_ADMIN_TOKEN: "{{ lookup('env', 'INFLUXDB_ADMIN_TOKEN') }}"
    BACKUP_S3_BUCKET: "{{ lookup('env', 'BACKUP_S3_BUCKET') }}"
    BACKUP_S3_ENDPOINT: "{{ lookup('env', 'BACKUP_S3_ENDPOINT') }}"
    FOUNDRY_ADMIN_KEY: "{{ lookup('env', 'FOUNDRY_ADMIN_KEY') }}"
    KOFI_VERIFICATION: "{{ lookup('env', 'KOFI_VERIFICATION') }}"
    JWT_SHARED_KEY: "{{ lookup('env', 'JWT_SHARED_KEY') }}"
    management_api_secret: "{{ lookup('password', '/dev/null', chars=['ascii_letters', 'digits']) }}"
    api_secret: "{{ lookup('password', '/dev/null', chars=['ascii_letters', 'digits']) }}"
    foundry_s3_config:
      accessKeyId: "{{ lookup('env', 'FOUNDRY_S3_ACCESS_KEY_ID') }}"
      secretAccessKey: "{{ lookup('env', 'FOUNDRY_S3_SECRET_KEY') }}"
