all:
  vars:
    telegraf_agent_version: "2.0.7"
    docker_compose_version: "1.29.2"
    foundry_extensible_plugin_version: "2.3.0"

    foundry_docker_image: ishtanzar/wm-docker-foundry:2.0.0
    management_api_image: ishtanzar/wm-management-api:0.8.1
    api_image: ishtanzar/wm-api:0.4.0
    discordbot_image: ishtanzar/wm-discord-bot:0.14.0
    worker_image: ishtanzar/wm-worker:0.3.1
    discord_workaround_image: ishtanzar/wm-discord-workaround:0.4.2
