version: "3.8"

services:
  influxdb:
    image: influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=p@ssw0rd
      - DOCKER_INFLUXDB_INIT_ORG=westmarchesdelacave
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=t0ken
  grafana:
    image: grafana/grafana
    volumes:
      - ./wm-infra/modules/main/ansible/roles/westmarches/templates/grafana-dashboards.tpl.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./wm-infra/deploy/local/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./wm-infra/modules/main/ansible/roles/westmarches/files/grafana-dashboards:/var/lib/grafana/dashboards:ro
    links:
      - influxdb
    ports:
      - "3000:3000"
  telegraf:
    image: telegraf:latest
    volumes:
    - ./wm-infra/deploy/local/telegraf.toml:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
  foundry:
    build:
      context: wm-infra/docker/foundry
    volumes:
      - /home/pgmillon/workspace/FoundryVTT/app:/home/foundry/resources/app
      - ./wm-infra/docker/foundry/data:/data
      - ./wm-backend-plugin:/home/foundry/resources/wm-backend-plugin
    command: ["--require", "/home/foundry/resources/wm-backend-plugin", "resources/app/main.js", "--port=30000", "--headless", "--noupdate", "--dataPath=/data"]
    ports:
      - "30000:30000"
  manager_api:
    build:
      context: wm-manager-api/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt
    command: ["python", "/opt/wm-manager-api/src/__main__.py"]
    ports:
      - "5000:5000"
    environment:
      - COMPOSE_DIR=/opt
      - HTPASSWD_PATH=/opt/tests/resources/.htpasswd
  discordbot:
    build:
      context: wm-discord-speaker/
    links:
      - manager_api
    volumes:
      - ./wm-discord-speaker/src:/opt/wm-discord-speaker
      - ./wm-discord-speaker/data:/opt/redbot/data
      - ./tests/resources/redbot-config.json:/root/.config/Red-DiscordBot/config.json
      - ./wm-infra/modules/main/ansible/roles/discordbot/files/default-intents.json:/opt/default-intents.json
    environment:
      - FOUNDRY_HOST=manager_api
      - MANAGER_API_SECRET=changeme
      - DEFAULT_INTENTS_PATH=/opt/default-intents.json
    command: ["redbot", "westmarches", "--mentionable", "--token=${DISCORD_BOT_SECRET}", "--prefix=YVwWFZyjiFQH"]