version: "3.8"

services:
  foundry:
    image: ubuntu
    command: tail -f /dev/null
  manager_api:
    build:
      context: wm-manager-api/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt
    command: ["python", "/opt/wm-manager-api/src/__main__.py"]
    ports:
      - "5000:5000"
    environment:
      - COMPOSE_DIR=/opt
      - HTPASSWD_PATH=/opt/tests/resources/.htpasswd
  discordbot:
    build:
      context: wm-discord-speaker/
    links:
      - manager_api
    volumes:
      - ./wm-discord-speaker/src:/opt/wm-discord-speaker
      - ./wm-discord-speaker/data:/opt/redbot/data
      - ./tests/resources/redbot-config.json:/root/.config/Red-DiscordBot/config.json
      - ./wm-infra/modules/main/ansible/roles/discordbot/files/default-intents.json:/opt/default-intents.json
    environment:
      - FOUNDRY_HOST=manager_api
      - MANAGER_API_SECRET=changeme
      - DEFAULT_INTENTS_PATH=/opt/default-intents.json
    command: ["redbot", "westmarches", "--mentionable", "--token=${DISCORD_BOT_SECRET}", "--prefix=YVwWFZyjiFQH"]