version: "3.8"

services:
  influxdb:
    image: influxdb:2.0.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=p@ssw0rd
      - DOCKER_INFLUXDB_INIT_ORG=westmarchesdelacave
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=t0ken
  grafana:
    image: grafana/grafana:main
    volumes:
      - ./wm-infra/modules/main/ansible/roles/westmarches/templates/grafana-dashboards.tpl.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./wm-infra/deploy/local/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./wm-infra/modules/main/ansible/roles/westmarches/files/grafana-dashboards:/var/lib/grafana/dashboards:ro
    links:
      - influxdb
    ports:
      - "3000:3000"
  telegraf:
    image: telegraf:1.18.3
    volumes:
      - ./wm-infra/deploy/local/telegraf.toml:/etc/telegraf/telegraf.conf:ro
      - foundry-logs:/logs/foundry
    links:
      - influxdb
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=BUH8JVS2CJYK8HH22UI6-XIP
      - MINIO_ROOT_PASSWORD=tchtIVtvwW2EICkqzD4wh_KzdRcxVrJ9VmzB8NizmDTKH1Ra
    command: server /data
    ports:
      - "9000:9000"
  foundry:
    build:
      context: wm-infra/docker/foundry
    environment:
      - FOUNDRY_WORLD=west-marches-de-la-cave
    volumes:
      - /home/pgmillon/workspace/FoundryVTT/app:/home/foundry/resources/app
      - ./wm-infra/deploy/local/data/foundry/Data:/data/Data
      - ./wm-infra/deploy/local/data/foundry/Config:/data/Config
      - foundry-logs:/data/Logs
      - ./wm-backend-plugin:/home/foundry/resources/wm-backend-plugin
    command: ["--require", "/home/foundry/resources/wm-backend-plugin", "resources/app/main.js", "--port=30000", "--headless", "--noupdate", "--dataPath=/data"]
    ports:
      - "30000:30000"
  manager_api:
    build:
      context: wm-manager-api/
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/opt/project
      - /var/run/docker.sock:/var/run/docker.sock
      - ./wm-infra/deploy/local/data/foundry/Data:/data/foundry
      - ./wm-infra/deploy/local/data/api:/data/api
      - ./wm-infra/deploy/local/api-logging.yml:/etc/logging.yml
    command: ["python", "/opt/project/wm-manager-api/src/__main__.py"]
    ports:
      - "5000:5000"
    environment:
      - COMPOSE_DIR=/opt/project
      - HTPASSWD_PATH=/opt/wm-manager-api/test/resources/.htpasswd
      - FOUNDRY_DATA_PATH=/data/foundry
      - FOUNDRY_ENDPOINT=http://foundry:30000
      - BACKUP_S3_BUCKET=backups
      - BACKUP_S3_ENDPOINT=http://minio:9000/
      - DATABASE_ENDPOINT=lightning:///data/api/westmarches.db
      - LOGGING_CONFIG=/etc/logging.yml
      - AWS_ACCESS_KEY_ID=BUH8JVS2CJYK8HH22UI6-XIP
      - AWS_SECRET_ACCESS_KEY=tchtIVtvwW2EICkqzD4wh_KzdRcxVrJ9VmzB8NizmDTKH1Ra
    links:
      - minio
      - foundry
  discordbot:
    build:
      context: wm-discord-speaker/
    links:
      - manager_api
    volumes:
      - ./:/opt/project
      - ./wm-infra/deploy/local/data/discord:/opt/redbot/data
      - ./wm-infra/deploy/local/redbot-config.json:/root/.config/Red-DiscordBot/config.json
      - ./wm-infra/deploy/local/discordbot-logging.yml:/opt/discordbot-logging.yml
      - ./wm-infra/modules/main/ansible/roles/discordbot/files/default-intents.json:/opt/default-intents.json
    environment:
      - WM_API_SECRET=changeme
      - WM_API_ENDPOINT=http://manager_api:5000
      - LOGGING_CONFIG=/opt/discordbot-logging.yml
      - DEFAULT_INTENTS_PATH=/opt/default-intents.json
    command: ["redbot", "westmarches", "--mentionable", "--token=${DISCORD_BOT_SECRET}", "--prefix=YVwWFZyjiFQH", "--owner=${DISCORD_OWNER_ID}"]

volumes:
  foundry-logs: