foundryvtt_zip: foundryvtt-0.7.9.zip
foundry_data_path: /opt/data/foundry
foundry_timezone: Europe/Paris
foundry_language: fr.tidy5e-sheet
foundry_world: west-marches-de-la-cave
foundry_hostname: westmarchesdelacave
foundry_domain: ishtanzar.net
foundry_fqdn: "{{ foundry_hostname }}.{{ foundry_domain }}"
foundry_docker_image: ishtanzar/wm-foundry:latest

manager_api_secret: changeme
manager_api_docker_image: ishtanzar/wm-manager-api:latest

foundry_s3_bucket: caveduroliste-westmarches
FOUNDRY_BUCKET_ACCESS_KEY_ID: ''
FOUNDRY_BUCKET_SECRET_ACCESS_KEY: ''
