
- name: Install base packages
  ansible.builtin.apt:
    pkg:
      - awscli
      - python3-pip
      - python3-boto3
      - python3-docker
      - unzip
      - zip
      - snapd
    state: present
    update_cache: yes

- name: Install pip packages
  ansible.builtin.pip:
    name:
      - awscli_plugin_endpoint
      - passlib

- name: AWS folder exists
  ansible.builtin.file:
    path: /root/.aws
    state: directory
