- name: Template docker-compose file
  ansible.builtin.template:
    src: "{{ docker_compose.src }}"
    dest: "{{ docker_compose.dest }}"

- name: Template unit file
  ansible.builtin.template:
    src: "{{ unit.src }}"
    dest: "/etc/systemd/system/{{ unit.name }}"
    owner: root
    group: root
    mode: '0644'
  register: unit_file_status

- name: Reload Systemd
  systemd:
    name: "{{ unit.name }}"
    enabled: true
    daemon_reload: true
  when: unit_file_status.changed

- name: Ensure data folder exists
  file:
    path: "{{ data_path }}"
    state: directory

#- name: Restart service
#  systemd:
#    name: "{{ unit.name }}"
#    state: restarted

