# {{ ansible_managed }}
version: "3.8"

services:
  web:
    build:
      context: .
    image: kanka
    container_name: kanka
    ports:
      - ${DOCKER_WEB_PORT}:80
    env_file:
      - .docker/web/variables.env
    environment:
      APP_DEBUG: ${APP_DEBUG}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      DB_HOST: database
      # DB_CONNECTION: mysql
      # DB_DATABASE: kanka_test
      # DB_USERNAME: homestead
      # DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - database
      - redis

  database:
    image: mariadb:10
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
  
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379

volumes:
  mariadb_data:
