version: 1

disable_existing_loggers: False

root:
  handlers:
    - jsonFile
    - console
  level: DEBUG

loggers:
  botocore:
    level: INFO
  docker:
    level: INFO
  h5py:
    level: INFO

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    (): logging_utilities.formatters.json_formatter.JsonFormatter
    add_always_extra: True

handlers:
  jsonFile:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: /opt/project/wm-infra/deploy/local/data/api/api-json.log
    backupCount: 1
    maxBytes: 1048576
    level: INFO
  
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
    level: DEBUG
