- name: Set repository access_key
  community.docker.docker_container_exec:
    container: "{{ elasticsearch_ctnr }}"
    command: /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.scw_par.access_key -f --stdin
    stdin: "{{ SCW_ACCESS_KEY }}"

- name: Set repository secret_key
  community.docker.docker_container_exec:
    container: "{{ elasticsearch_ctnr }}"
    command: /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.scw_par.secret_key -f --stdin
    stdin: "{{ SCW_SECRET_KEY }}"

- name: Reload secrets
  ansible.builtin.uri:
    url: "http://{{ elasticsearch_ip }}:9200/_nodes/reload_secure_settings"
    method: POST

- name: Create snapshot repository
  ansible.builtin.uri:
    url: "http://{{ elasticsearch_ip }}:9200/_snapshot/scw_object_store"
    method: PUT
    body_format: json
    body:
      type: s3
      settings:
        client: scw_par
        bucket: westmarches-backups
        base_path: elasticsearch

- name: Create SLM policy
  ansible.builtin.uri:
    url: "http://{{ elasticsearch_ip }}:9200/_slm/policy/nightly-snapshots"
    method: PUT
    body_format: json
    body:
      schedule: "0 30 4 * * ?"
      name: "<nightly-snap-{now/d}>"
      repository: scw_object_store
      config:
        indices: "*"
        include_global_state: true
      retention:
        expire_after: 30d
        min_count: 5
        max_count: 50
