
- name: Fetch foundry-extensible-plugin
  ansible.builtin.get_url:
    url: "{{ lookup('env', 'FOUNDRY_EXTENSIBLE_PLUGIN_URL')|default(extensible_plugin_url, True) }}"
    dest: "{{ westmarches_data_path }}/foundry-extensible-plugin.zip"
    url_username: "{{ lookup('env', 'GITHUB_USER') }}"
    url_password: "{{ lookup('env', 'GITHUB_PASSWORD') }}"
    force_basic_auth: yes
    timeout: 60
    force: yes

- ansible.builtin.file:
    path: "{{ westmarches_data_path }}/foundry-extensible-plugin"
    state: absent

- ansible.builtin.file:
    path: "{{ westmarches_data_path }}/foundry-extensible-plugin"
    state: directory

- name: Unarchive foundry-extensible-plugin
  ansible.builtin.unarchive:
    src: "{{ westmarches_data_path }}/foundry-extensible-plugin.zip"
    dest: "{{ westmarches_data_path }}/foundry-extensible-plugin"
    remote_src: yes

- ansible.builtin.file:
    path: "{{ westmarches_data_path }}/foundry-extensible-plugin.zip"
    state: absent
