
- name: Create data path
  ansible.builtin.file:
    path: "{{ westmarches_data_path }}"
    state: directory

- name: Template proxy conf
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: custom.tpl.nginx, dest: "{{ westmarches_data_path }}/nginx.conf" }
    - { src: docker-compose.tpl.yml, dest: "{{ westmarches_data_path }}/docker-compose.yml" }
    - { src: prometheus.tpl.yml, dest: "{{ westmarches_data_path }}/prometheus.yml" }
    - { src: grafana-datasources.tpl.yml, dest: "{{ westmarches_data_path }}/grafana-datasources.yml" }
    - { src: grafana.tpl.ini, dest: "{{ westmarches_data_path }}/grafana.ini" }

- name: Template unit file
  ansible.builtin.template:
    src: westmarches.service
    dest: "/etc/systemd/system/westmarches.service"
    owner: root
    group: root
    mode: '0644'
  vars:
    compose_files:
      - "{{ foundry_data_path }}-compose.yml"
      - "{{ westmarches_data_path }}/docker-compose.yml"
  register: unit_file_status

- name: Reload Systemd
  systemd:
    name: westmarches.service
    enabled: true
    daemon_reload: true
  when: unit_file_status.changed
