
- name: Look for playtest container info
  community.docker.docker_host_info:
    containers: true
    containers_filters:
      label:
        - com.docker.compose.project=playtest
        - com.docker.compose.service=playtest
  register: compose_playtest_facts

- ansible.builtin.set_fact:
    playtest_running: "{{ compose_playtest_facts | json_query('containers') | length > 0 }}"

- name: Gather playtest container facts
  community.docker.docker_container_info:
    name: "{{ compose_playtest_facts | json_query('containers[0].Id') }}"
  when: playtest_running
  register: playtest_container_facts
