version: 1

disable_existing_loggers: False

root:
  handlers:
    - jsonFile
    - console
  level: DEBUG
  propagate: True


formatters:
  json:
    (): logging_utilities.formatters.json_formatter.JsonFormatter
    add_always_extra: True

handlers:
  jsonFile:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: /opt/data/api/api-json.log
    backupCount: 1
    maxBytes: 1048576
    level: INFO
  
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: INFO
