# {{ ansible_managed }}
version: "3.8"

secrets:
  config_json:
    file: "{{ foundry_data_path }}/secrets.json"

services:
  foundry:
    image: "{{ foundry_docker_image }}"
    init: true
    restart: "unless-stopped"
    volumes:
      - "{{ foundry_data_path }}:/data"
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_PATCHES=/data/container_patches
      - "TIMEZONE={{ foundry_timezone }}"
      - "FOUNDRY_HOSTNAME={{ foundry_fqdn }}"
      - "FOUNDRY_LANGUAGE={{ foundry_language }}"
      - "FOUNDRY_WORLD={{ foundry_world }}"
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
    healthcheck:
      test: curl localhost:30000/api/status || exit -1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    secrets:
      - source: config_json
        target: config.json
    ports:
      - "30000"
  manager_api:
    image: "{{ manager_api_docker_image }}"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ foundry_data_path }}-compose.yml:/opt/docker-compose.yml"
      - "{{ foundry_data_path }}/.htpasswd:/opt/.htpasswd"
      - "{{ foundry_data_path }}/Data:/data/foundry"
    secrets:
      - source: config_json
        target: /opt/data/foundry/secrets.json
    ports:
      - "5000"
    environment:
      - COMPOSE_DIR=/opt
      - HTPASSWD_PATH=/opt/.htpasswd
      - FOUNDRY_DATA_PATH=/data/foundry
      - "BACKUP_S3_BUCKET={{ BACKUP_S3_BUCKET }}"
