# {{ ansible_managed }}
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:0.7.9
#    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: "{{ data_path }}"
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_PATCHES=/data/container_patches
      - TIMEZONE=Europe/Paris
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
