
- name: Lookup Data device
  ansible.builtin.set_fact:
    SCW_DATA_VOLUME: "/dev/{{ ansible_devices|dict2items|json_query('[].{dev: key, ids: join(`,`, value.links.ids)}[?contains(ids, `' + SCW_VOLUME_ID + '`)]|[0].dev' )}}"

- name: "Create {{ SCW_DATA_VOLUME }} partition"
  community.general.parted:
    device: "{{ SCW_DATA_VOLUME }}"
    number: 1
    fs_type: ext4
    state: present

- name: "Create a ext4 filesystem on {{ SCW_DATA_VOLUME }}"
  community.general.filesystem:
    fstype: ext4
    dev: "{{ SCW_DATA_VOLUME }}1"

- name: Mount point exists
  ansible.builtin.file:
    path: /opt/data
    state: directory

- name: "Mount {{ SCW_DATA_VOLUME }}"
  ansible.posix.mount:
    path: /opt/data
    src: "{{ SCW_DATA_VOLUME }}1"
    fstype: ext4
    state: mounted

- name: Create some paths
  ansible.builtin.file:
    path: "{{ foundry_data_path }}/{{ item }}"
    state: directory
  loop:
    - container_cache
    - container_patches/resources

- name: Fetch foundry
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "private/foundryvtt/{{ foundryvtt_zip }}"
    dest: "{{ foundry_data_path }}/container_cache/{{ foundryvtt_zip }}"
    s3_url: https://s3.fr-par.scw.cloud
    region: fr-par
    aws_access_key: "{{ SCW_ACCESS_KEY }}"
    aws_secret_key: "{{ SCW_SECRET_KEY }}"
    mode: get

- name: Fetch patch resources
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "private/foundryvtt/patch/0-7-9/{{ item }}"
    dest: "{{ foundry_data_path }}/container_patches/resources/{{ item }}"
    s3_url: https://s3.fr-par.scw.cloud
    region: fr-par
    aws_access_key: "{{ SCW_ACCESS_KEY }}"
    aws_secret_key: "{{ SCW_SECRET_KEY }}"
    mode: get
  loop:
    - auth.js
    - init.js
    
- name: Upload patches
  ansible.builtin.copy:
    src: patches/custom.sh
    dest: "{{ foundry_data_path }}/container_patches/"

- name: Upload secrets file
  ansible.builtin.copy:
    src: secrets.json
    dest: "{{ foundry_data_path }}/secrets.json"

- name: Manager API htpasswd file
  community.general.htpasswd:
    name: foundry_manager
    password: "{{ manager_api_secret }}"
    path: "{{ foundry_data_path }}/.htpasswd"

- name: Template docker-compose file
  ansible.builtin.template:
    src: docker-compose.tpl.yml
    dest: "{{ foundry_data_path }}-compose.yml"
