- set_fact:
    foundry_src_templates: "{{ role_path }}/templates"

- name: Create some paths
  ansible.builtin.file:
    path: "{{ foundry_data_path }}/{{ item }}"
    state: directory
  loop:
    - container_cache
    - container_patches/resources

- name: Fetch foundry
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "private/foundryvtt/{{ foundryvtt_zip }}"
    dest: "{{ foundry_data_path }}/container_cache/{{ foundryvtt_zip }}"
    s3_url: https://s3.fr-par.scw.cloud
    region: fr-par
    aws_access_key: "{{ SCW_ACCESS_KEY }}"
    aws_secret_key: "{{ SCW_SECRET_KEY }}"
    mode: get

- name: Fetch patch resources
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "private/foundryvtt/patch/0-7-9/{{ item }}"
    dest: "{{ foundry_data_path }}/container_patches/resources/{{ item }}"
    s3_url: https://s3.fr-par.scw.cloud
    region: fr-par
    aws_access_key: "{{ SCW_ACCESS_KEY }}"
    aws_secret_key: "{{ SCW_SECRET_KEY }}"
    mode: get
  loop:
    - auth.js
    - init.js
    
- name: Upload patches
  ansible.builtin.copy:
    src: patches/custom.sh
    dest: "{{ foundry_data_path }}/container_patches/"
    
- name: Systemd unit
  include_role:
    name: systemd
    tasks_from: unit
  vars:
    docker_compose:
      src: "{{ foundry_src_templates }}/docker-compose.tpl.yml"
      dest: "{{ foundry_data_path }}-compose.yml"
    unit:
      src: "{{ foundry_src_templates }}/foundry.service"
      name: foundry.service
    data_path: "{{ foundry_data_path }}"
