
- name: Pre-tasks
  hosts: all
  pre_tasks:
    - assert:
        that:
          - lookup('env', 'SCW_VOLUME_ID')
          - lookup('env', 'SCW_ACCESS_KEY')
          - lookup('env', 'SCW_SECRET_KEY')
  roles:
    - base-system
    - cloudalchemy.node_exporter
  post_tasks:
    - ansible.builtin.set_fact:
        SCW_ACCESS_KEY: "{{ lookup('env', 'SCW_ACCESS_KEY') }}"
        SCW_SECRET_KEY: "{{ lookup('env', 'SCW_SECRET_KEY') }}"
        SCW_VOLUME_ID: "{{ lookup('env', 'SCW_VOLUME_ID') }}"

    - name: AWS config
      ansible.builtin.template:
        src: aws_config
        dest: /root/.aws/config

    - name: AWS credentials
      ansible.builtin.template:
        src: aws_credentials
        dest: /root/.aws/credentials

- name: FoundryVTT
  hosts: foundry
  roles:
    - docker
    - foundry
    - westmarches
