- hosts: all
  gather_facts: no
  tasks:
  
    - name: Create some paths
      ansible.builtin.file:
        path: "{{ foundry_data_path }}/{{ item }}"
        state: directory
        owner: 421
        group: 421
      loop:
        - Data/systems
        - Data/modules
        - Config

    - name: Cleanup modules
      include_role:
        name: foundry
        tasks_from: modules_cleanup.yml

    - name: Install modules
      include_role:
        name: foundry
        tasks_from: module_install.yml
      loop: "{{ foundry_modules }}"
      loop_control:
        loop_var: module

# Broken for some reason
#    - name: Install extensible module
#      include_role:
#        name: westmarches
#        tasks_from: extensible-plugin.yml
