name: foundry-extensible-plugin

on:
  push:
    paths:
      - .github/workflows/foundry-extensible-plugin.yml
      - foundry-extensible-plugin/**
    branches:
      - '**'
    tags:
      - 'releases/foundry-extensible-plugin/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Github tag
        id: github_tag
        run: echo ::set-output name=GITHUB_TAG::${GITHUB_REF/refs\/tags\/releases\/foundry-extensible-plugin\/v/}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm install
        working-directory: foundry-extensible-plugin
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: contains(github.ref, 'main')
        with:
          name: foundry-extensible-plugin-main
          path: foundry-extensible-plugin

      - name: Create release archive
        if: contains(github.ref, 'refs/tags')
        working-directory: foundry-extensible-plugin
        run: zip -r foundry-extensible-plugin-${{ steps.github_tag.outputs.GITHUB_TAG }}.zip . --exclude \*.iml

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, 'refs/tags')
        with:
          files: foundry-extensible-plugin/foundry-extensible-plugin-${{ steps.github_tag.outputs.GITHUB_TAG }}.zip